'use strict';
var cities = {
	'Bratislavský': [
		'Bratislava - Staré Mesto',
		'Bratislava - Podunajské Biskupice',
		'Bratislava - Ružinov',
		'Bratislava - Vrakuňa',
		'Bratislava - Nové Mesto',
		'Bratislava - Rača',
		'Bratislava - Vajnory',
		'Bratislava - Devín',
		'Bratislava - Devínska Nová Ves',
		'Bratislava - Dúbravka',
		'Bratislava - Karlova Ves',
		'Bratislava - Lamač',
		'Bratislava - Záhorská Bystrica',
		'Bratislava - Čunovo',
		'Bratislava - Jarovce',
		'Bratislava - Petržalka',
		'Bratislava - Rusovce',
		'Borinka',
		'Gajary',
		'Jablonové',
		'Jakubov',
		'Kostolište',
		'Kuchyňa',
		'Láb',
		'Lozorno',
		'Malacky',
		'Malé Leváre',
		'Marianka',
		'Pernek',
		'Plavecké Podhradie',
		'Plavecký Mikuláš',
		'Plavecký Štvrtok',
		'Rohožník',
		'Sološnica',
		'Studienka',
		'Stupava',
		'Suchohrad',
		'Veľké Leváre',
		'Vysoká pri Morave',
		'Záhorie (vojenský obvod)',
		'Záhorská Ves',
		'Závod',
		'Zohor',
		'Báhoň',
		'Budmerice',
		'Častá',
		'Doľany',
		'Dubová',
		'Jablonec',
		'Limbach',
		'Modra',
		'Pezinok',
		'Píla',
		'Slovenský Grob',
		'Svätý Jur',
		'Šenkvice',
		'Štefanová',
		'Viničné',
		'Vinosady',
		'Vištuk',
		'Bernolákovo',
		'Blatné',
		'Boldog',
		'Čataj',
		'Dunajská Lužná',
		'Hamuliakovo',
		'Hrubá Borša',
		'Hrubý Šúr',
		'Hurbanova Ves',
		'Chorvátsky Grob',
		'Igram',
		'Ivanka pri Dunaji',
		'Kalinkovo',
		'Kaplna',
		'Kostolná pri Dunaji',
		'Kráľová pri Senci',
		'Malinovo',
		'Miloslavov',
		'Most pri Bratislave',
		'Nová Dedinka',
		'Nový Svet',
		'Reca',
		'Rovinka',
		'Senec',
		'Tomášov',
		'Tureň',
		'Veľký Biel',
		'Vlky',
		'Zálesie'
	],
	'Trnavský' : [
		'Báč',
		'Baka',
		'Baloň',
		'Bellova Ves',
		'Blahová',
		'Blatná na Ostrove',
		'Bodíky',
		'Boheľov',
		'Čakany',
		'Čenkovce',
		'Čiližská Radvaň',
		'Dobrohošť',
		'Dolný Bar',
		'Dolný Štál',
		'Dunajská Streda',
		'Dunajský Klátov',
		'Gabčíkovo',
		'Holice',
		'Horná Potôň',
		'Horné Mýto',
		'Horný Bar',
		'Hubice',
		'Hviezdoslavov',
		'Jahodná',
		'Janíky',
		'Jurová',
		'Kľúčovec',
		'Kostolné Kračany',
		'Kráľovičove Kračany',
		'Kútniky',
		'Kvetoslavov',
		'Kyselica',
		'Lehnice',
		'Lúč na Ostrove',
		'Macov',
		'Mad',
		'Malé Dvorníky',
		'Medveďov',
		'Mierovo',
		'Michal na Ostrove',
		'Ňárad',
		'Nový Život',
		'Ohrady',
		'Okoč',
		'Oľdza',
		'Orechová Potôň',
		'Padáň',
		'Pataš',
		'Potônske Lúky',
		'Povoda',
		'Rohovce',
		'Sap',
		'Šamorín',
		'Štvrtok na Ostrove',
		'Topoľníky',
		'Trhová Hradská',
		'Trnávka',
		'Trstená na Ostrove',
		'Veľká Paka',
		'Veľké Blahovo',
		'Veľké Dvorníky',
		'Veľký Meder',
		'Vieska',
		'Vojka nad Dunajom',
		'Vrakúň',
		'Vydrany',
		'Zlaté Klasy',
		'Abrahám',
		'Čierna Voda',
		'Čierny Brod',
		'Dolná Streda',
		'Dolné Saliby',
		'Dolný Chotár',
		'Galanta',
		'Gáň',
		'Horné Saliby',
		'Hoste',
		'Jánovce',
		'Jelka',
		'Kajal',
		'Košúty',
		'Kráľov Brod',
		'Malá Mača',
		'Matúškovo',
		'Mostová',
		'Pata',
		'Pusté Sady',
		'Pusté Úľany',
		'Sereď',
		'Sládkovičovo',
		'Šalgočka',
		'Šintava',
		'Šoporňa',
		'Tomášikovo',
		'Topoľnica',
		'Trstice',
		'Váhovce',
		'Veľká Mača',
		'Veľké Úľany',
		'Veľký Grob',
		'Vinohrady nad Váhom',
		'Vozokany',
		'Zemianske Sady',
		'Bojničky',
		'Červeník',
		'Dolné Otrokovce',
		'Dolné Trhovište',
		'Dolné Zelenice',
		'Dvorníky',
		'Hlohovec',
		'Horné Otrokovce',
		'Horné Trhovište',
		'Horné Zelenice',
		'Jalšové',
		'Kľačany',
		'Koplotovce',
		'Leopoldov',
		'Madunice',
		'Merašice',
		'Pastuchov',
		'Ratkovce',
		'Sasinkovo',
		'Siladice',
		'Tekolďany',
		'Tepličky',
		'Trakovice',
		'Žlkovce',
		'Banka',
		'Bašovce',
		'Borovce',
		'Dolný Lopašov',
		'Drahovce',
		'Dubovany',
		'Ducové',
		'Hubina',
		'Chtelnica',
		'Kočín - Lančár',
		'Krakovany',
		'Moravany nad Váhom',
		'Nižná',
		'Ostrov',
		'Pečeňady',
		'Piešťany',
		'Prašník',
		'Rakovice',
		'Ratnovce',
		'Sokolovce',
		'Šípkové',
		'Šterusy',
		'Trebatice',
		'Veľké Kostoľany',
		'Veľké Orvište',
		'Veselé',
		'Vrbové',
		'Bílkove Humence',
		'Borský Mikuláš',
		'Borský Svätý Jur',
		'Cerová',
		'Čáry',
		'Častkov',
		'Dojč',
		'Hlboké',
		'Hradište pod Vrátnom',
		'Jablonica',
		'Koválov',
		'Kuklov',
		'Kúty',
		'Lakšárska Nová Ves',
		'Moravský Svätý Ján',
		'Osuské',
		'Plavecký Peter',
		'Podbranč',
		'Prietrž',
		'Prievaly',
		'Rohov',
		'Rovensko',
		'Rybky',
		'Sekule',
		'Senica',
		'Smolinské',
		'Smrdáky',
		'Sobotište',
		'Šajdíkove Humence',
		'Šaštín - Stráže',
		'Štefanov',
		'Brodské',
		'Dubovce',
		'Gbely',
		'Holíč',
		'Chropov',
		'Kátov',
		'Kopčany',
		'Koválovec',
		'Letničie',
		'Lopašov',
		'Mokrý Háj',
		'Oreské',
		'Petrova Ves',
		'Popudinské Močidľany',
		'Prietržka',
		'Radimov',
		'Radošovce',
		'Skalica',
		'Trnovec',
		'Unín',
		'Vrádište',
		'Biely Kostol',
		'Bíňovce',
		'Bohdanovce nad Trnavou',
		'Boleráz',
		'Borová',
		'Brestovany',
		'Bučany',
		'Buková',
		'Cífer',
		'Dechtice',
		'Dlhá',
		'Dobrá Voda',
		'Dolná Krupá',
		'Dolné Dubové',
		'Dolné Lovčice',
		'Dolné Orešany',
		'Horná Krupá',
		'Horné Dubové',
		'Horné Orešany',
		'Hrnčiarovce nad Parnou',
		'Jaslovské Bohunice',
		'Kátlovce',
		'Košolná',
		'Križovany nad Dudváhom',
		'Lošonec',
		'Majcichov',
		'Malženice',
		'Naháč',
		'Opoj',
		'Pavlice',
		'Radošovce',
		'Ružindol',
		'Slovenská Nová Ves',
		'Smolenice',
		'Suchá nad Parnou',
		'Šelpice',
		'Špačince',
		'Šúrovce',
		'Trnava',
		'Trstín',
		'Vlčkovce',
		'Voderady',
		'Zavar',
		'Zeleneč',
		'Zvončín'
	]
};

module.exports = cities;
module.exports.cities = function () {

};
